// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PlayerBrawlerStats struct {
	ID          string  `json:"id"`
	BrawlerName string  `json:"brawlerName"`
	WinLoss     float64 `json:"winLoss"`
	Wins        int     `json:"wins"`
	Losses      int     `json:"losses"`
}

type PlayerInput struct {
	PlayerCode string `json:"playerCode"`
}
